### ISSUE TITLE
Support Lambda@Edge 

### ISSUE THREAD

**Issue by ispyinternet** [H4ad/serverless-adapter#101]
Does anyone know if this supports Lambda@Edge out of the box?

I think the event structures are different to Api Gateway Lambda and I'm not even sure about Lambda HTTP connect.

Yh I'd be interested on some feedback regarding this. Thanks.

**Comment by ispyinternet** [comment]
ah ok, just found this: https://github.com/H4ad/serverless-adapter/blob/main/src/adapters/aws/lambda-edge.adapter.ts

**Comment by H4ad** [comment]
@ispyinternet I never used this integration with Lambda Edge before and I'm not sure if the abstraction is good, let me know if you have any issues with it.

Before you, I never thought anyone would be interested in running NodeJS Frameworks on Lambda@edge, so I'm very happy for any feedback on this integration.

**Comment by ispyinternet** [comment]
Hi @H4ad,

So here are the results:

the code:

```
import { ServerlessAdapter } from '@h4ad/serverless-adapter';
import { LambdaEdgeAdapter } from '@h4ad/serverless-adapter/lib/adapters/aws';
import { TrpcFramework } from '@h4ad/serverless-adapter/lib/frameworks/trpc';
import { DefaultHandler } from '@h4ad/serverless-adapter/lib/handlers/default';
import { PromiseResolver } from '@h4ad/serverless-adapter/lib/resolvers/promise';
import { TrpcAdapterContext, TrpcFrameworkOptions } from '@h4ad/serverless-adapter/lib/frameworks/trpc';
import { initTRPC } from '@trpc/server';
import routes from '$lib/trpc/router/routes';

type CustomContext = { currentDate: Date };
type TrpcContext = TrpcAdapterContext<CustomContext>;

const frameworkOptions: TrpcFrameworkOptions<TrpcContext> = {
  createContext: () => ({ currentDate: new Date() }),
};

const framework = new TrpcFramework<TrpcContext>(frameworkOptions);

const t = initTRPC.context<TrpcContext>().create();

const appRouter = t.router(routes(t.router,t.middleware,t.procedure));

const h = ServerlessAdapter.new(appRouter)
  .setFramework(framework)
  .setHandler(new DefaultHandler())
  .setResolver(new PromiseResolver())
  .addAdapter(new LambdaEdgeAdapter())
  .build();

export const handler = async (e,c) => {

        // remove the trpc prefix on the uri
	e.Records[0].cf.request.uri = e.Records[0].cf.request.uri.substr(5);
	const body = await h(e,c);

	// remove disallowed response headers
	delete e.Records[0].cf.request.headers['host'];
	delete e.Records[0].cf.request.headers['transfer-encoding'];
	delete e.Records[0].cf.request.headers['via'];
	delete e.Records[0].cf.request.headers['content-length'];
	
	return {
          body: JSON.stringify(body),
          bodyEncoding: 'text',
          headers: { ...e.Records[0].cf.request.headers },
          status: '200',
          statusDescription: 'Success'
       };
}
```

My Lambda@Edge responds to viewer-request events on the `/trpc` path. Notice how in the handler, I have to remove the `trcp` prefix from the URI, otherwise the trpc server will not process the route correctly (it tries to include trpc as part of the route namespace i.e. `trpc.books.author`. I'm new to trpc, so not sure if there is a configuration to tell the trpc server what base path it is using, also trying to work out if this is an issue related to the client I am using (see discussion https://github.com/icflorescu/trpc-sveltekit/discussions/87)

I had to construct the response object myself, my expectations were for the LambdaEdgeAdapter to construct this for me - should it?

Correct me if I'm wrong, but I don't seem to need to use the JsonBodyFramework (as per examples I followed)?

Otherwise, thanks for a great library!

**Comment by ispyinternet** [comment]
Following up, it looks like mutations aren't working. Error:

`"stack": "TRPCError: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"undefined\",\n    \"path\": [],\n    \"message\": \"Required\"\n  }\n]\n    at inputMiddleware (/var/task/index.js:30605:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async callRecursive (/var/task/index.js:30782:32)\n    at async resolve (/var/task/index.js:30812:24)\n    at async inputToProcedureCall (/var/task/index.js:30080:22)\n    at async Promise.all (index 0)\n    at async resolveHTTPResponse (/var/task/index.js:30207:37)\n    at async /var/task/index.js:30456:9"`

which seems very similar to this users error msg: https://github.com/trpc/trpc/discussions/1553

Which was a json decoding issue, but I do have the `JsonBodyParserFramework` included.

**Comment by H4ad** [comment]
As I understand it, you want to use Lambda@Edge so that your tRPC framework returns responses on the edge.

But, shouldn't Lambda@Edge only be used with Cloudfront to return/modify files from Cloudfront/S3?

From what I've seen, you want to use like vercel, and that adapter wasn't written to match that behavior, which is why my adapter expects you to return the headers, body, etc...

I will reopen this issue as I think we can come up with a better adapter to handle your case. Can you provide some basic steps to build everything needed on the AWS side? From what I understand, I need to create a Cloudfront, setup a path of `trpc` and then redirect that path to my lambda, right?

**Comment by H4ad** [comment]
I added the initial code for this feature on #104, if you want to beta test it, just copy this file: https://github.com/H4ad/serverless-adapter/blob/526f119dd2096503e42810bd3c99274307f99f7d/src/adapters/aws/viewer-request-lambda-edge.adapter.ts to your project and remove the `LambdaEdgeAdapter` and put this one in the same place.

**Comment by ispyinternet** [comment]
Perfect, all issues fixed and now super clean code.

Do you still want me to provide you with some files to setup on aws? I've got a codepipeline project, but its a little convulated because it uses a custom cloudformation resource to trigger from a private bitbucket, but I can strip it down to give you something to work with?

**Comment by ispyinternet** [comment]
A couple of questions:

1. you don't return `statusDescription` - doesn't bother me, but perhaps others may desire?
2. is there a way to add additional headers to the response? (again perhaps others will require)

**Comment by H4ad** [comment]
You don't need to provide code, I already figure out how to properly configure the Cloudfront.

About your questions:

- 1: The status description is optional, if you send a correct status code, it will fill the status description with the correct message.
- 2: There is, see [tRPC Context](https://github.com/H4ad/serverless-adapter/blob/main/src/frameworks/trpc/trpc.framework.ts#L52-L110), you can use those methods by acessing it in the context, I'm using it [here](https://github.com/H4ad/serverless-adapter-examples/blob/master/examples/trpc-aws/src/setup.ts#L23-L26).

A few considerations for the current implementation, if you configure Cloudfront to render a different status code in the error pages, it will affect the `/trpc` endpoint. I had a problem that the error page was configured to render `index.html` in status `400`, so my `POST` request returned an empty message every time an error occurred on validation.

**Comment by ispyinternet** [comment]
ah ok, i'll have to see how that plays out and work out how to handle. Its a userland problem with userland options/solutions right?

**Comment by ispyinternet** [comment]
So your example shows how to access the request headers / context, but can we add additional headers to the response?

**Comment by H4ad** [comment]
@ispyinternet I recommend you move from `viewer-request` to `origin-request`, your lambda could have more memory and can take more time to process the request.

Also, on `origin-request`, you can use `cache-control` to control the cache of your response, `viewer-request` never cache the response.

The only issue I found is if make a request fast enough, it will return a cache even if you explicitly say to not cache.

**Comment by H4ad** [comment]
Thank you for your feedback, I think the Lambda@Edge adapter is much better now than before, if you have any questions about this, please don't hesitate to get in touch.
