### ISSUE TITLE
API Gateway Context Object in tRPC

### ISSUE THREAD

**Issue by ispyinternet** [H4ad/serverless-adapter#122]
Hi, can you provide a gist of how to get the ApiGateway context object onto the tRPC context?

**Comment by H4ad** [comment]
Inside your `trpc` method, you can call [getCurrentInvoke](https://serverless-adapter.viniciusl.com.br/docs/api/Core/Current%20Invoke/getCurrentInvoke), it will returns the context and also the event object that you received before the transformation to call your framework.

**Comment by H4ad** [comment]
I think this issue is solved, so I will close it for now, feel free to open it again if you have any other questions.
