### ISSUE TITLE
LazyFramework should rethrow exception throwed by factory function

### ISSUE THREAD

**Issue by kaito3desuyo** [H4ad/serverless-adapter#188]
## Current Behavior

Based on the LazyFramework sample, I used the factory function to initialize the OpenID Connect client.

```
import { ServerlessAdapter } from '@h4ad/serverless-adapter';
import { AlbAdapter, ApiGatewayV1Adapter } from '@h4ad/serverless-adapter/lib/adapters/aws';
import { FastifyFramework } from '@h4ad/serverless-adapter/lib/frameworks/fastify';
import { LazyFramework } from '@h4ad/serverless-adapter/lib/frameworks/lazy';
import { DefaultHandler } from '@h4ad/serverless-adapter/lib/handlers/default';
import { PromiseResolver } from '@h4ad/serverless-adapter/lib/resolvers/promise';
import app from '@libs/presentations/app';
import { InitializerUtil } from '@utils/initializer';

async function bootstrap() {
    await InitializerUtil.initialize(); // <-- Initialize OpenID Client
    return app;
}

const fastify = new FastifyFramework();
const framework = new LazyFramework(fastify, bootstrap);

export const main = ServerlessAdapter.new(null)
    .setFramework(framework)
    .setHandler(new DefaultHandler())
    .setResolver(new PromiseResolver())
    .addAdapter(process.env.IS_OFFLINE ? new ApiGatewayV1Adapter() : new AlbAdapter())
    .build();
```

However, in rare cases, a timeout exception may occur due to poor connectivity to the OIDC provider.

```
RPError: outgoing request timed out after 3500ms
    at /opt/nodejs/node_modules/openid-client/lib/helpers/request.js:137:13
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:509:9)
    at async Issuer.discover (/opt/nodejs/node_modules/openid-client/lib/issuer.js:171:22)
    at Object.init (/src/libs/gateways/openid.ts:16:20)
    at async Promise.all (index 1)
    at Object.initialize (/src/utils/initializer.ts:5:5)
    at bootstrap (/src/functions/authentication-api/handler.ts:11:5)
```

In this case, Lambda's Init phase should fail, but because LazyFramework catches the exception that occurs, the Init phase is treated as successful.

https://github.com/H4ad/serverless-adapter/blob/main/src/frameworks/lazy/lazy.framework.ts#L55

## Expected Behavior

Lambda's Init phase should fail if an exception occurs within the factory function.

## Environment

- Version: 2.17.0
- Platform: Linux (WSL2 Ubuntu 20.04)
- Node.js Version: 18.14.2

**Comment by H4ad** [comment]
This is something that can't be solved by this library, what you can do is convert your application to `esm` and use the `top level await`, then you will be able to wait and if fails, crash your lambda and force to restart.

The `LazyFramework` will only act after your lambda inits, and any message error you will only after you make any request, the only way to crash the init phase during an exception is with `top level await`.

**Comment by kaito3desuyo** [comment]
@H4ad Thank you for your answer.
I had a vague idea that it might be that way.
Looks like it's time to support ES Modules...
I see what needs to be done, so I will close this issue. Thanks a lot.
