### ISSUE TITLE
how to use tRPC with Lambda?

### ISSUE THREAD

**Issue by cyrfer** [H4ad/serverless-adapter#43]
This repo looks amazing. I'm trying to find examples to use tRPC with AWS Lambda. I know the tRPC project advertises support for Lambda, but I see Typescript compile errors when I try.

Do you have a tRCP/Lambda sample?

Thank you!

**Comment by H4ad** [comment]
Have you tried the examples inside https://github.com/H4ad/serverless-adapter-examples/tree/master/src/trpc?

**Comment by H4ad** [comment]
@cyrfer Hey, I created a better working example with tRPC and AWS Lambda, you can easily run and deploy, see more here: https://github.com/H4ad/serverless-adapter-examples/tree/feature/better-examples/ examples /trpc-aws

**Comment by H4ad** [comment]
I'll close this now and consider it answered, if you have any other questions feel free to open another issue.
